name: build proj

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: node:24
        steps:
            - uses: actions/checkout@v4
            with:
                node-version: 24
            - run: npm ci
            - run: npm install
            - run: npm run build
            